const express = require("express");
const { createOrder, getOrders, getOrderById, updateOrder, deleteOrder } = require("../controllers/orderController");
const { authenticate } = require("../middleware/authMiddleware");
const router = express.Router();
router.post("/", authenticate, createOrder);
router.get("/", authenticate, getOrders);
router.get("/:id", authenticate, getOrderById);
router.put("/:id", authenticate, updateOrder);
router.delete("/:id", authenticate, deleteOrder);
module.exports = router;